//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWCFClient.demoMathsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="demoMathsService.IMathsService")]
    public interface IMathsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathsService/Add", ReplyAction="http://tempuri.org/IMathsService/AddResponse")]
        int Add(MyWCF.Domain.Math obj);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMathsService/Add", ReplyAction="http://tempuri.org/IMathsService/AddResponse")]
        System.IAsyncResult BeginAdd(MyWCF.Domain.Math obj, System.AsyncCallback callback, object asyncState);
        
        int EndAdd(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathsService/Sub", ReplyAction="http://tempuri.org/IMathsService/SubResponse")]
        int Sub(MyWCF.Domain.Math obj);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMathsService/Sub", ReplyAction="http://tempuri.org/IMathsService/SubResponse")]
        System.IAsyncResult BeginSub(MyWCF.Domain.Math obj, System.AsyncCallback callback, object asyncState);
        
        int EndSub(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMathsServiceChannel : MyWCFClient.demoMathsService.IMathsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SubCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MathsServiceClient : System.ServiceModel.ClientBase<MyWCFClient.demoMathsService.IMathsService>, MyWCFClient.demoMathsService.IMathsService {
        
        private BeginOperationDelegate onBeginAddDelegate;
        
        private EndOperationDelegate onEndAddDelegate;
        
        private System.Threading.SendOrPostCallback onAddCompletedDelegate;
        
        private BeginOperationDelegate onBeginSubDelegate;
        
        private EndOperationDelegate onEndSubDelegate;
        
        private System.Threading.SendOrPostCallback onSubCompletedDelegate;
        
        public MathsServiceClient() {
        }
        
        public MathsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MathsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MathsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MathsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<AddCompletedEventArgs> AddCompleted;
        
        public event System.EventHandler<SubCompletedEventArgs> SubCompleted;
        
        public int Add(MyWCF.Domain.Math obj) {
            return base.Channel.Add(obj);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAdd(MyWCF.Domain.Math obj, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAdd(obj, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndAdd(System.IAsyncResult result) {
            return base.Channel.EndAdd(result);
        }
        
        private System.IAsyncResult OnBeginAdd(object[] inValues, System.AsyncCallback callback, object asyncState) {
            MyWCF.Domain.Math obj = ((MyWCF.Domain.Math)(inValues[0]));
            return this.BeginAdd(obj, callback, asyncState);
        }
        
        private object[] OnEndAdd(System.IAsyncResult result) {
            int retVal = this.EndAdd(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddCompleted(object state) {
            if ((this.AddCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddCompleted(this, new AddCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddAsync(MyWCF.Domain.Math obj) {
            this.AddAsync(obj, null);
        }
        
        public void AddAsync(MyWCF.Domain.Math obj, object userState) {
            if ((this.onBeginAddDelegate == null)) {
                this.onBeginAddDelegate = new BeginOperationDelegate(this.OnBeginAdd);
            }
            if ((this.onEndAddDelegate == null)) {
                this.onEndAddDelegate = new EndOperationDelegate(this.OnEndAdd);
            }
            if ((this.onAddCompletedDelegate == null)) {
                this.onAddCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddCompleted);
            }
            base.InvokeAsync(this.onBeginAddDelegate, new object[] {
                        obj}, this.onEndAddDelegate, this.onAddCompletedDelegate, userState);
        }
        
        public int Sub(MyWCF.Domain.Math obj) {
            return base.Channel.Sub(obj);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSub(MyWCF.Domain.Math obj, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSub(obj, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndSub(System.IAsyncResult result) {
            return base.Channel.EndSub(result);
        }
        
        private System.IAsyncResult OnBeginSub(object[] inValues, System.AsyncCallback callback, object asyncState) {
            MyWCF.Domain.Math obj = ((MyWCF.Domain.Math)(inValues[0]));
            return this.BeginSub(obj, callback, asyncState);
        }
        
        private object[] OnEndSub(System.IAsyncResult result) {
            int retVal = this.EndSub(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSubCompleted(object state) {
            if ((this.SubCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SubCompleted(this, new SubCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SubAsync(MyWCF.Domain.Math obj) {
            this.SubAsync(obj, null);
        }
        
        public void SubAsync(MyWCF.Domain.Math obj, object userState) {
            if ((this.onBeginSubDelegate == null)) {
                this.onBeginSubDelegate = new BeginOperationDelegate(this.OnBeginSub);
            }
            if ((this.onEndSubDelegate == null)) {
                this.onEndSubDelegate = new EndOperationDelegate(this.OnEndSub);
            }
            if ((this.onSubCompletedDelegate == null)) {
                this.onSubCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSubCompleted);
            }
            base.InvokeAsync(this.onBeginSubDelegate, new object[] {
                        obj}, this.onEndSubDelegate, this.onSubCompletedDelegate, userState);
        }
    }
}
