//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWCFClient.taskAsyncService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="taskAsyncService.IMathsService")]
    public interface IMathsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathsService/Add", ReplyAction="http://tempuri.org/IMathsService/AddResponse")]
        int Add(MyWCF.Domain.Math obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathsService/Add", ReplyAction="http://tempuri.org/IMathsService/AddResponse")]
        System.Threading.Tasks.Task<int> AddAsync(MyWCF.Domain.Math obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathsService/Sub", ReplyAction="http://tempuri.org/IMathsService/SubResponse")]
        int Sub(MyWCF.Domain.Math obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathsService/Sub", ReplyAction="http://tempuri.org/IMathsService/SubResponse")]
        System.Threading.Tasks.Task<int> SubAsync(MyWCF.Domain.Math obj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMathsServiceChannel : MyWCFClient.taskAsyncService.IMathsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MathsServiceClient : System.ServiceModel.ClientBase<MyWCFClient.taskAsyncService.IMathsService>, MyWCFClient.taskAsyncService.IMathsService {
        
        public MathsServiceClient() {
        }
        
        public MathsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MathsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MathsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MathsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add(MyWCF.Domain.Math obj) {
            return base.Channel.Add(obj);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(MyWCF.Domain.Math obj) {
            return base.Channel.AddAsync(obj);
        }
        
        public int Sub(MyWCF.Domain.Math obj) {
            return base.Channel.Sub(obj);
        }
        
        public System.Threading.Tasks.Task<int> SubAsync(MyWCF.Domain.Math obj) {
            return base.Channel.SubAsync(obj);
        }
    }
}
